### ISSUE TITLE
Debian package causes warning on every `apt update`: Policy will reject signature within a year

### ISSUE THREAD

**Issue by brainsik** [MisterTea/EternalTerminal#702]
After installing the et Debian package, every time I run `apt update` I see the following warning:

```txt
Warning: https://mistertea.github.io/debian-et/debian-source/dists/trixie/InRelease: Policy will reject signature within a year, see --audit for details
```

Running with `--audit` shows:

```txt
Audit: https://mistertea.github.io/debian-et/debian-source/dists/trixie/InRelease: Sub-process /usr/bin/sqv returned an error code (1), error message is:
   Signing key on 1B7807C5BEBF69CB10E66BD6F965077657E85C2D is not bound:
              No binding signature at time 2024-05-05T17:08:45Z
     because: Policy rejected non-revocation signature (PositiveCertification) requiring second pre-image resistance
     because: SHA1 is not considered secure since 2026-02-01T00:00:00Z
```

----
Debian 13 (trixie) using the 6.2.9-trixie1 Debian package.

**Comment by jniggemann** [comment]
## Underlying cause
Internally, apt uses "Sequoia PGP" to verify signatures - hence the message that `/usr/bin/sqv` returnes an error code in your example above. By default, sqv is configured to accept the (old and broken) SHA1 hash algorithm only until Feb 1st 2026.

## How to resolve this issue
There's nothing you can do besides raising awareness for this issue.  
This issue can only be resolved by the project team, who need to change their repo signing key to one that does not use SHA1. 

## How to temporarily suppress this warning until this repo uses another key
To reconfigure `sqv`, copy `/usr/share/apt/default-sequoia.config` to `/etc/crypto-policies/back-ends/apt-sequoia.config`, and change the date in the last line from 2026-02-01 to ex. 2027-02-01. ([more](https://book.sequoia-pgp.org/configuration.html))

Please think about possible implications and do not forget to revert this, once the project team has switched to another key.

**Comment by shampeon** [comment]
The previous comment is not relevant as far as this issue is concerned. The underlying cause is that the key you used to sign the packages uses the old, insecure SHA1 algorithm, and will stop working. So you need to generate a new key and use that to sign the packages. See the [Debian packaging docs](https://wiki.debian.org/DebianRepository/Format#Size.2C_MD5sum.2C_SHA1.2C_SHA256.2C_SHA512).

The previous comment was how the _user_ can suppress the warning.

**Comment by shampeon** [comment]
```
❯ sudo apt update
Hit:1 http://deb.debian.org/debian trixie-backports InRelease
Hit:2 http://security.debian.org/debian-security trixie-security InRelease
Hit:3 http://mirrors.ocf.berkeley.edu/debian trixie InRelease
Hit:4 http://mirrors.ocf.berkeley.edu/debian trixie-updates InRelease
Get:5 https://mistertea.github.io/debian-et/debian-source trixie InRelease [10.4 kB]
Hit:6 https://download.docker.com/linux/debian trixie InRelease
Err:5 https://mistertea.github.io/debian-et/debian-source trixie InRelease
  Sub-process /usr/bin/sqv returned an error code (1), error message is: Signing key on 1B7807C5BEBF69CB10E66BD6F965077657E85C2D is not bound:            No binding signature at time 2026-02-03T05:07:47Z   because: Policy rejected non-revocation signature (PositiveCertification) requiring second pre-image resistance   because: SHA1 is not considered secure since 2026-02-01T00:00:00Z
Hit:7 https://download.vscodium.com/debs vscodium InRelease
Hit:8 http://download.opensuse.org/repositories/graphics:/darktable/Debian_13  InRelease
Get:9 https://pkgs.tailscale.com/stable/debian trixie InRelease
Fetched 6,582 B in 0s (13.3 kB/s)
All packages are up to date.
Warning: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. OpenPGP signature verification failed: https://mistertea.github.io/debian-et/debian-source trixie InRelease: Sub-process /usr/bin/sqv returned an error code (1), error message is: Signing key on 1B7807C5BEBF69CB10E66BD6F965077657E85C2D is not bound:            No binding signature at time 2026-02-03T05:07:47Z   because: Policy rejected non-revocation signature (PositiveCertification) requiring second pre-image resistance   because: SHA1 is not considered secure since 2026-02-01T00:00:00Z
Warning: Failed to fetch https://mistertea.github.io/debian-et/debian-source/dists/trixie/InRelease  Sub-process /usr/bin/sqv returned an error code (1), error message is: Signing key on 1B7807C5BEBF69CB10E66BD6F965077657E85C2D is not bound:            No binding signature at time 2026-02-03T05:07:47Z   because: Policy rejected non-revocation signature (PositiveCertification) requiring second pre-image resistance   because: SHA1 is not considered secure since 2026-02-01T00:00:00Z
Warning: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by MisterTea** [comment]
Ok thanks, I see the error now. I'll rebuild with a new gpg key and report back tonight or tomorrow

**Comment by moxli** [comment]
@MisterTea unfortunately the issue still persists for me. 
I also redownloaded the gpg key.

```
Warning: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. OpenPGP signature verification failed: https://mistertea.github.io/debian-et/debian-source trixie InRelease: Sub-process /usr/bin/sqv returned an error code (1), error message is: Signing key on 1B7807C5BEBF69CB10E66BD6F965077657E85C2D is not bound:            No binding signature at time 2026-02-05T07:56:54Z   because: Policy rejected non-revocation signature (PositiveCertification) requiring second pre-image resistance   because: SHA1 is not considered secure since 2026-02-01T00:00:00Z

Warning: Failed to fetch https://mistertea.github.io/debian-et/debian-source/dists/trixie/InRelease  Sub-process /usr/bin/sqv returned an error code (1), error message is: Signing key on 1B7807C5BEBF69CB10E66BD6F965077657E85C2D is not bound:            No binding signature at time 2026-02-05T07:56:54Z   because: Policy rejected non-revocation signature (PositiveCertification) requiring second pre-image resistance   because: SHA1 is not considered secure since 2026-02-01T00:00:00Z

Warning: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by Rongronggg9** [comment]
> A separate issue is that the Debian instructions should put the key in `/etc/apt/trusted.gpg.d/et.gpg`, as that's the correct location for additional keys.

That's incorrect:

> If it will be managed locally , it SHOULD be downloaded into `/etc/apt/keyrings` instead.
> --- https://wiki.debian.org/DebianRepository/UseThirdParty#OpenPGP_certificate_distribution

I made this mistake in #530, so please don't repeat it.
